from datetime import date
import time
import random


def invoiceGeneratorReturn(name, costume, quantity, charge, day, fine):
    timeStr = time.strftime("%Y%m%d-%H%M%S")
    nameTimeStr = name+timeStr
    randomNum = random.randint(0, 1000)
    floatFine = float(fine)
    floatCharge = float(charge)
    totalCharge = floatCharge+ floatFine
   
    with open("./invoiceReturn/"+nameTimeStr+".txt", 'w') as f:
        f.write(f""" 
        |--------------------------------------------------------------------------------------------|
        |                                 Python Rental Shop                                        
        |                                      Kathmandu -8                                          
        |                                                                                            
        |                         Phone: 021-545-840 || Fax:(828)349-5900                            
        |                                                                                                           |                                                                                          
        |                                                                                            
        |  Kathmandu , Nepal                                            Invoice id: {randomNum}            
        |  rental12@gmail.com                                           Invoice date: {date.today()}     
        |                                                                                            
        |                       Returned invoice generated by Costume Rental shop                      
        |                                                                                            
        |     Description                                                                            
        |____________________________________________________________________________________________
        |                                                                                            
        | Dear {name},                                                                          
        |    Thank you for returning the {costume},                                              
        |     of quantity {quantity}.                                                              
        |    Total days with time from the date, you rent is {day}. 
        |    If total days is greater than 5 we fine 1000$. 
        |    Hence,The total fine you need to pay is {floatFine}$.
        |    The total price is {totalCharge}$                          
        |                                                                                            
        |                             Thank you for choosing us !!!                                  
        |                                                                                            
        |                                                                                
        |                                                                                    
        |                                                                                    
        |                                                                                            
        |                                                                                            
        |                                                                       __________________   
        |                                                                          Python CEO    
        |                                                                                            
        |____________________________________________________________________________________________|
    """)
