from datetime import date
import time
import random


def invoiceGenerator(name, address, phone, totalPrice, costume, brand):
    timeStr = time.strftime("%Y%m%d-%H%M%S")
    nameTimeStr = name+timeStr
    randomNum = random.randint(0, 1000)
    with open("./invoiceRent/"+nameTimeStr+".txt", 'w') as f:
        f.write(f""" 
        |--------------------------------------------------------------------------------------------|
        |                                 Python Rental Shop                                        
        |                                      Kathmandu -8                                          
        |                                                                                            
        |                         Phone: 021-545-840 || Fax:(828)349-5900                            
        |                                                                                                           |                                                                                          
        |                                                                                            
        |  Kathmandu , Nepal                                            Invoice id: {randomNum}            
        |  rental12@gmail.com                                           Invoice date: {date.today()}     
        |                                                                                            
        |                       Rented invoice generated by Costume Rental shop                      
        |                                                                                            
        |     Description                                                                            
        |____________________________________________________________________________________________
        |                                                                                            
        | Dear {name},                                                                          
        |    Thank you for renting the {costume},                                              
        |               By brand "{brand}"                                                                 
        |    You've made an excellent decision. The entire cost is {totalPrice}$.                            
        |                                                                                            
        |                             Thank you for choosing us !!!                                  
        |                                                                                            
        | Your Details                                                                               
        |   {address}                                                                                    
        |   {phone}                                                                                   
        |          
        |        Note: 1000$ fine will be charged if you returned costume after more than 5 days    
        |                                                                      
        |                                                                          
        |
        |
        |                                                                       __________________   
        |                                                                          Python CEO     
        |                                                                                            
        |____________________________________________________________________________________________|
    """)
